#!/bin/bash
IFS=$'\t'
: "${SORTBY:=date}"
case "$SORTBY" in
  date) STYPE="-rn";;
  date-asc) STYPE="-n";;
  title) STYPE="-k4";;
esac
# TSV output: Unix-Time mdfile htmlfile title "Month DD, YYYY"
# Sorted by Date
listarticles () {
  for NAME in articles/*.md; do
  DATE="$(date -d $(lowdown -X date "$NAME") "+%s")"
  printf "%s\t%s\t%s\t%s\t%s\n"  "$DATE" "$NAME" "${NAME/.md/.html}" \
    "$(lowdown -X title "$NAME")" "$(date -d "@$DATE" "+%B %d, %Y")"
  done | sort $STYPE
}

htmllist() {
  echo "<ul>"
  listarticles | while read -r UTIME OLDFILE NEWFILE TITLE DATE; do
    printf "<li><a href=\"%s\">%s</a> (%s)</li>\n" "$NEWFILE" "$TITLE" "$DATE"
  done
  echo "</ul>"
}

rssfeed () {
  echo "<rss version=\"2.0\"><channel>"
  echo "<title>$WEBSNAME</title>"
  echo "<link>$WEBSURL</link>"
  echo "<language>en</language>"
  listarticles | while read UNIXDATE OLDFILE NEWFILE TITLE DATE; do
    printf "<item><title>%s</title>\n" "$TITLE"
    echo "<link>$WEBSURL$NEWFILE</link>"
    echo "<pubDate>$(date -d @$UNIXDATE "+%a, %d %b %Y %T %z")</pubDate>"
    echo "<description>"
    ${MD:-lowdown} --html-no-{escape,skip}html $OLDFILE |\
      sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g'
    echo "</description></item>"
  done
  echo "</channel></rss>"
}

${1:-listarticles}
